export default [
  {
    _id: "RS101",
    name: "Rocket Propulsion",
    number: "RS4550",
    startDate: "2023-01-10",
    endDate: "2023-05-15",
    department: "D123",
    credits: 4,
    description:
      "This course provides an in-depth study of the fundamentals of rocket propulsion, covering topics such as propellant chemistry, engine design, and performance optimization.",
    author: "Dr. John Doe",
    image: "/images/reactjs.jpg",
  },
  {
    _id: "RS102",
    name: "Aerodynamics",
    number: "RS4560",
    startDate: "2023-01-10",
    endDate: "2023-05-15",
    department: "D123",
    credits: 3,
    description:
      "This course offers a comprehensive exploration of aerodynamics, focusing on the principles and applications of airflow and its effects on flying objects.",
    author: "Dr. Jane Smith",
    image: "/images/reactjs.jpg",
  },
  {
    _id: "RS103",
    name: "Spacecraft Design",
    number: "RS4570",
    startDate: "2023-01-10",
    endDate: "2023-05-15",
    department: "D123",
    credits: 4,
    description:
      "This course delves into the principles and practices of designing spacecraft for various missions, including satellite and deep-space exploration vehicles.",
    author: "Dr. Emily Clark",
    image: "/images/reactjs.jpg",
  },
  {
    _id: "RS104",
    name: "Organic Chemistry",
    number: "CH1230",
    startDate: "2023-01-10",
    endDate: "2023-05-15",
    department: "D134",
    credits: 3,
    description:
      "Organic Chemistry is an in-depth study of the structure, properties, and reactions of organic compounds and materials.",
    author: "Dr. Alan Turing",
    image: "/images/reactjs.jpg",
  },
  {
    _id: "RS105",
    name: "Inorganic Chemistry",
    number: "CH1240",
    startDate: "2023-01-10",
    endDate: "2023-05-15",
    department: "D134",
    credits: 3,
    description:
      "Inorganic Chemistry focuses on the properties, structures, and behaviors of inorganic and organometallic compounds.",
    author: "Dr. Marie Curie",
    image: "/images/reactjs.jpg",
  },
  {
    _id: "RS106",
    name: "Physical Chemistry",
    number: "CH1250",
    startDate: "2023-01-10",
    endDate: "2023-05-15",
    department: "D134",
    credits: 3,
    description:
      "Physical Chemistry bridges the gap between chemistry and physics, exploring the physical principles underlying chemical processes.",
    author: "Dr. Niels Bohr",
    image: "/images/reactjs.jpg",
  },
  {
    _id: "RS107",
    name: "Ancient Languages",
    number: "LA1010",
    startDate: "2023-01-10",
    endDate: "2023-05-15",
    department: "D145",
    credits: 3,
    description:
      "This course explores the languages of ancient civilizations, including Latin, Ancient Greek, and Sanskrit, and their influence on modern languages.",
    author: "Dr. Linguistics",
    image: "/images/reactjs.jpg",
  },
];
